# Generated by Django 5.1.6 on 2025-03-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('role', models.CharField(choices=[('USER', 'Regular User'), ('ADMIN', 'Administrator'), ('MODERATOR', 'Moderator')], default='USER', max_length=20)),
                ('phone_number', models.CharField(help_text='Format: 09123456789', max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('firstname', models.CharField(blank=True, max_length=200, verbose_name='first name')),
                ('lastname', models.CharField(blank=True, max_length=200, verbose_name='last name')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
