# Generated by Django 5.1.6 on 2025-03-11 11:58

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 11, 57, 39, 281980, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
