# Generated by Django 5.1.6 on 2025-03-11 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_expire_profile_verification_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 11, 12, 10, 55, 958898, tzinfo=datetime.timezone.utc)),
        ),
    ]
