# Generated by Django 5.1.6 on 2025-03-14 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 14, 13, 2, 20, 825789, tzinfo=datetime.timezone.utc)),
        ),
    ]
