# Generated by Django 5.1.6 on 2025-03-16 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_profile_expire"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="email_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="account",
            name="phone_number_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 16, 17, 29, 37, 553108, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
