# Generated by Django 5.1.6 on 2025-03-16 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_account_email_active_account_phone_number_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_verification_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 16, 17, 52, 29, 695029, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
