<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-18 11:18
=======
# Generated by Django 5.1.7 on 2025-03-20 13:54
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("account", "0008_alter_profile_email_verification_token_and_more"),
=======
        ('account', '0008_alter_profile_email_verification_token_and_more'),
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="profile",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 18, 11, 23, 58, 433322, tzinfo=datetime.timezone.utc
                )
            ),
=======
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 13, 59, 28, 462368, tzinfo=datetime.timezone.utc)),
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e
        ),
    ]
