# Generated by Django 5.1.7 on 2025-03-20 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profile_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 13, 59, 28, 462368, tzinfo=datetime.timezone.utc)),
        ),
    ]
