# Generated by Django 5.1.7 on 2025-03-20 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 18, 57, 39, 296487, tzinfo=datetime.timezone.utc)),
        ),
    ]
