# Generated by Django 5.1.7 on 2025-03-20 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 19, 36, 56, 762281, tzinfo=datetime.timezone.utc)),
        ),
    ]
