# Generated by Django 5.1.7 on 2025-03-22 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 9, 4, 41, 341774, tzinfo=datetime.timezone.utc)),
        ),
    ]
