# Generated by Django 5.1.7 on 2025-03-22 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 9, 30, 44, 927718, tzinfo=datetime.timezone.utc)),
        ),
    ]
