# Generated by Django 5.1.7 on 2025-03-22 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 15, 9, 54, 709273, tzinfo=datetime.timezone.utc)),
        ),
    ]
