# Generated by Django 5.1.7 on 2025-03-23 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_profile_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 11, 23, 31, 438743, tzinfo=datetime.timezone.utc)),
        ),
    ]
