# Generated by Django 5.1.7 on 2025-03-30 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_alter_profile_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 30, 11, 27, 42, 820741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
