# Generated by Django 5.1.7 on 2025-04-04 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_alter_profile_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="expire",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 4, 12, 41, 28, 806115, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
