# Generated by Django 5.1.6 on 2025-03-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membermodel_is_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='phone_number',
            field=models.CharField(default='09212155738', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
