# Generated by Django 5.1.6 on 2025-03-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
