# Generated by Django 5.1.7 on 2025-03-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_payment_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
