# Generated by Django 5.1.6 on 2025-03-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_unit_price_product_price_and_more'),
        ('users', '0002_alter_membermodel_is_active_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(related_name='users', to='users.membermodel'),
        ),
    ]
