<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-18 11:18
=======
# Generated by Django 5.1.7 on 2025-03-20 13:54
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("products", "0003_alter_product_users"),
=======
        ('products', '0003_alter_product_users'),
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="comment",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
=======
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
>>>>>>> ac53f22605bdd1acb494b502ec0d5b4ddbd2a56e
        ),
    ]
