# Generated by Django 5.1.7 on 2025-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_comment_product_alter_product_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productaudio",
            name="audio",
            field=models.FileField(upload_to="product/audios"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product/images"),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="video",
            field=models.FileField(upload_to="product/videos"),
        ),
    ]
