# Generated by Django 5.1.6 on 2025-03-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
